### ISSUE TITLE
Python 3.9.10 Windows 10

### ISSUE THREAD

**Issue by hokaspb** [DiffSK/configobj#216]
C:\>python --version
Python 3.9.10

C:\>python -m pip install configobj
Collecting configobj
  Using cached configobj-5.0.6.tar.gz (33 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-install-99ops59j\configobj_a9220cc1b110451a94fdbfd80073a71b\setup.py", line 17, in <module>
          from _version import __version__
      ModuleNotFoundError: No module named '_version'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\admin>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\admin\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\Windows\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
HOMEDRIVE=C:
HOMEPATH=\Users\admin
LOCALAPPDATA=C:\Users\admin\AppData\Local
NUMBER_OF_PROCESSORS=8
OneDrive=C:\Users\admin\OneDrive
OS=Windows_NT
Path=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Python39;C:\Python39\Scripts;C:\Python39\Lib;C:\Python39\Lib\site-packages;C:\Users\admin\AppData\Local\Microsoft\WindowsApps;
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e09
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PYTHONPATH=C:\Python39;C:\Python39\Lib;C:\Python39\Lib\site-packages
PY_HOME=C:\Python39
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\Windows
TEMP=C:\Users\admin\AppData\Local\Temp
TMP=C:\Users\admin\AppData\Local\Temp

C:\Users\admin>pip freeze
appdirs==1.4.4
attrs==21.4.0
cattrs==1.10.0
certifi==2021.10.8
chardet==3.0.4
charset-normalizer==2.0.12
comtypes==1.1.11
googletrans==3.0.0
h11==0.9.0
h2==3.2.0
hpack==3.0.0
hstspreload==2021.12.1
html5lib==1.1
httpcore==0.9.1
httpx==0.13.3
hyperframe==5.2.0
idna==2.10
inflection==0.5.1
lxml==4.7.1
more-itertools==8.12.0
Nasdaq-Data-Link==1.0.1
numpy==1.22.2
OpenCC==1.1.1
packaging==21.3
pandas==1.4.1
pandas-datareader==0.10.0
pandas-datareaders-unofficial==0.0.4
patsy==0.5.2
Pillow==9.0.1
pyparsing==3.0.7
PyPDF2==1.26.0
pypiwin32==223
pytesseract==0.3.9
python-dateutil==2.8.2
pyttsx3==2.90
pytz==2021.3
pywin32==303
requests==2.27.1
requests-cache==0.9.2
rfc3986==1.5.0
scipy==1.8.0
six==1.16.0
sniffio==1.2.0
statsmodels==0.13.2
url-normalize==1.4.3
urllib3==1.26.8
webencodings==0.5.1

**Comment by hokaspb** [comment]
In PyCharm 'setyp.py install' from git configobj-master (__version__ = '5.1.0') work normal.

**Comment by hokaspb** [comment]
It's common Python 3.9.10 bug on Windows 10. pip work with PATH (import) errors.  Some python packages has msi (or exe) installer that resolve this errors.
