### ISSUE TITLE
default section doesn't work correctly if the name is uppercased

### ISSUE THREAD

**Issue by maranha1** [DiffSK/configobj#58]
With small example program, config and spec files there appear to be several issues.
(1) validate() returns True though I'm expecting it to return false as my config file has JUNK set to an integer instead of a string. Changing the section name 'DEFAULT' to lowercase 'default' gives the expected error result.
(2) In the [channels] section if I repeat one of the sub-sections I get:
Traceback (most recent call last):
  File "./config.py", line 7, in <module>
    config = ConfigObj(infile="foo.cfg", configspec="foo.spec", unrepr=True)
  File "/home/glarms/python/examples/configobj/configobj.py", line 1229, in **init**
    self._load(infile, configspec)
  File "/home/glarms/python/examples/configobj/configobj.py", line 1318, in _load
    raise error
configobj.ConfigObjError: Parsing failed with several errors.
First error at line 12.

::::::::::::::
config.py
::::::::::::::
# !/usr/bin/python

import os, sys
from configobj import ConfigObj, ConfigObjError, flatten_errors
from validate import Validator, ValidateError

config = ConfigObj(infile="foo.cfg", configspec="foo.spec", unrepr=True)
print config.configspec

vtor = Validator()
results = config.validate(vtor, preserve_errors=True)
print "results=",
::::::::::::::
foo.cfg
::::::::::::::
 #
 # config file
 #

[DEFAULT]
  FOOBAR = "hello"
  JUNK = "world!"

[channels]
  [[SRB1-BRIB]]
    instance = 0
  [[OHLN-BRIB]]
    instance = 0
    off = True

::::::::::::::
foo.spec
::::::::::::::
# 
# spec file
# 

[DEFAULT]
  FOOBAR = string
  JUNK = integer

[channels]
  [[**many**]]
    instance = integer(default=0)

**Comment by robdennis** [comment]
this reads as backwards-incompatible so not including it in 5.1.0
